import cloudflare from "@astrojs/cloudflare";
import react from "@astrojs/react";
import { d1, r2, sandbox } from "@emdash-cms/cloudflare";
import { defineConfig } from "astro/config";
import emdash from "emdash/astro";

// Note: @astrojs/sitemap removed — it can't enumerate dynamic SSR routes,
// and it can't emit different sitemaps for the two domains served by this
// Worker (mygeekmac.com + mygeekpc.com). Sitemap and robots.txt are now
// generated by custom endpoints in src/pages/sitemap.xml.ts and
// src/pages/robots.txt.ts which read live from EmDash and branch on host.
export default defineConfig({
	output: "server",
	site: "https://mygeekmac.com",
	adapter: cloudflare(),
	image: {
		layout: "constrained",
		responsiveStyles: true,
	},
	integrations: [
		react(),
		emdash({
			database: d1({ binding: "DB", session: "auto" }),
			storage: r2({ binding: "MEDIA" }),
			sandboxRunner: sandbox(),
		}),
	],
	devToolbar: { enabled: false },
});
